import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

//to do
//complete website setup so you and mom can make websites - new design
//make custom forms for each edit data category type
//make drop down lists no padding
//
//
//
//
//
//




const geist = localFont({
  src: "./fonts/Geist.ttf",
  variable: "--geist",
});

const metadataInfo = {
  title: "Squaremax",
  description: "Generated by Max"
}

export const metadata: Metadata = {
  title: metadataInfo.title,
  description: metadataInfo.description,
  metadataBase: new URL('https://squaremaxtech.com'),
  openGraph: {
    title: metadataInfo.title,
    description: metadataInfo.description,
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geist.variable} antialiased`}
      >
        <SessionProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <Nav />

          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
