import { mkdir, readFile, unlink, writeFile } from "node:fs/promises"
import path from "node:path"
import { DeleteObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3"
import { env } from "@/lib/env"

//============================================================
// Object storage for uploaded media. Cloudflare R2 (S3 API) when
// the R2_* variables are set — the GROWTH-PLAN target, no egress
// fees; otherwise local disk under userUploadedData/ served by
// /api/uploads/[...key]. Same key layout either way, so moving
// to R2 later is a copy job, not a migration.
//============================================================

export const LOCAL_UPLOAD_DIR = path.join(process.cwd(), "userUploadedData")

export type StorageMode = "r2" | "local"

export function storageMode(): StorageMode {
    return env.R2_BUCKET !== undefined ? "r2" : "local"
}

//keys are generated by us, but the local reader takes them from the URL —
//keep them boring: lowercase, no traversal
export function isSafeKey(key: string): boolean {
    return /^[a-z0-9][a-z0-9/_.-]{0,240}$/.test(key) && !key.includes("..") && !key.includes("//")
}

let r2Client: S3Client | null = null
function r2(): S3Client {
    r2Client ??= new S3Client({
        region: "auto",
        endpoint: `https://${env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
        credentials: {
            accessKeyId: env.R2_ACCESS_KEY_ID ?? "",
            secretAccessKey: env.R2_SECRET_ACCESS_KEY ?? "",
        },
    })
    return r2Client
}

export function publicUrlFor(key: string): string {
    if (storageMode() === "r2") return `${(env.R2_PUBLIC_URL ?? "").replace(/\/$/, "")}/${key}`
    return `${env.SITE_URL}/api/uploads/${key}`
}

export async function putObject(key: string, body: Buffer, contentType: string): Promise<{ url: string }> {
    if (!isSafeKey(key)) throw new Error("invalid storage key")

    if (storageMode() === "r2") {
        await r2().send(new PutObjectCommand({
            Bucket: env.R2_BUCKET,
            Key: key,
            Body: body,
            ContentType: contentType,
            //keys are unique per upload, so the CDN may cache forever
            CacheControl: "public, max-age=31536000, immutable",
        }))
        return { url: publicUrlFor(key) }
    }

    const file = path.join(LOCAL_UPLOAD_DIR, key)
    await mkdir(path.dirname(file), { recursive: true })
    await writeFile(file, body)
    return { url: publicUrlFor(key) }
}

export async function deleteObject(key: string): Promise<void> {
    if (!isSafeKey(key)) return
    if (storageMode() === "r2") {
        await r2().send(new DeleteObjectCommand({ Bucket: env.R2_BUCKET, Key: key }))
        return
    }
    try {
        await unlink(path.join(LOCAL_UPLOAD_DIR, key))
    } catch {
        //already gone — nothing to do
    }
}

//local mode only: the bytes behind /api/uploads/{key}
export async function readLocalObject(key: string): Promise<Buffer | null> {
    if (!isSafeKey(key)) return null
    try {
        return await readFile(path.join(LOCAL_UPLOAD_DIR, key))
    } catch {
        return null
    }
}
